kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.storageClass.claimName }}
  name: {{ .Values.storageClass.claimName }}
  {{- else }}
  name: redis-nfs-claim-auto
  {{- end }}
  annotations:
    # 申明使用这个provisioner
    volume.beta.kubernetes.io/storage-class: "{{ .Values.storageClass.name }}"
    volume.beta.kubernetes.io/storage-provisioner: "{{ .Values.storageClass.provisionerName }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi