apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    {{- if .Values.redis.port }}
    - port: {{ .Values.redis.port }}
    {{ end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
